remote_theme: pmarsceill/just-the-docs
title: IoT ML Design Kit
description: 

baseurl: "/iot-ml-design-kit"
url: "https://datacentricdesign.github.io"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
