title: IoT ML Design Kit
description: 
theme: just-the-docs

url: https://datacentricdesign.github.io/iot-ml-design-kit

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
